In [3]:
import pandas as pd
import sys
from pathlib import Path
sys.path.append((Path.cwd().parent/"src").resolve().as_posix())

import settings as s
from langchain.embeddings import HuggingFaceEmbeddings

# Data

In [3]:
# Reload all CSVs
purchases_df = pd.read_csv(s.data_root_path / "purchases.csv")
inventory_df = pd.read_csv(s.data_root_path / "raw_material_inventory.csv")
bom_df = pd.read_csv(s.data_root_path / "bill_of_materials.csv")
production_schedule_df = pd.read_csv(s.data_root_path / "production_schedule.csv")
finished_goods_inventory_df = pd.read_csv(s.data_root_path / "finished_goods_inventory.csv")

In [4]:
purchases_df

,po_id,supplier,item_name,quantity,order_date,delivery_date
0,1,SteelCorp,Glass Bottles,427,2020-01-01 00:00:00,2020-01-05 00:00:00
1,2,FastenIt,Nylon Granules,435,2020-01-01 01:00:00,2020-01-05 01:00:00
2,3,PolyPlast,Diodes,215,2020-01-01 02:00:00,2020-01-05 02:00:00
3,4,SteelCorp,Concrete Blocks,138,2020-01-01 03:00:00,2020-01-05 03:00:00
4,5,FastenIt,Screws,195,2020-01-01 04:00:00,2020-01-05 04:00:00
...,...,...,...,...,...,...
49995,49996,SteelCorp,Hydrochloric Acid,156,2025-09-14 03:00:00,2025-09-18 03:00:00
49996,49997,PolyPlast,Jute Bags,379,2025-09-14 04:00:00,2025-09-18 04:00:00
49997,49998,SteelCorp,Acrylic Sheets,470,2025-09-14 05:00:00,2025-09-18 05:00:00
49998,49999,PolyPlast,Springs,205,2025-09-14 06:00:00,2025-09-18 06:00:00
49999,50000,SteelCorp,Nuts,142,2025-09-14 07:00:00,2025-09-18 07:00:00

In [5]:
inventory_df

,item_id,item_name,category,stock_level,reorder_point,lead_time_days,supplier
0,1,Steel Rods,Raw Material,368,113,10,BoxMakers
1,2,Aluminum Sheets,Raw Material,687,126,6,BoxMakers
2,3,Copper Wire,Raw Material,260,242,11,SteelCorp
3,4,Brass Fittings,Raw Material,651,150,10,PolyPlast
4,5,Iron Ingots,Raw Material,796,120,8,PolyPlast
...,...,...,...,...,...,...,...
85,86,Springs,Raw Material,710,221,6,FastenIt
86,87,Bearings,Raw Material,537,241,10,PolyPlast
87,88,Pins,Raw Material,213,137,13,SteelCorp
88,89,Clamps,Raw Material,488,287,9,BoxMakers
89,90,Seals,Raw Material,485,157,8,BoxMakers

In [6]:
bom_df

       product_name           raw_material  quantity_required
0         Car Frame                 Screws                  9
1         Car Frame              LED Chips                  9
2         Car Frame       Sodium Hydroxide                  6
3    Plastic Bottle                 Rivets                  4
4    Plastic Bottle  Polycarbonate Pellets                  6
5    Plastic Bottle             Capacitors                  3
6   Furniture Panel         Nylon Granules                  6
7   Furniture Panel                 Screws                  6
8   Furniture Panel  Polycarbonate Pellets                  5
9      Engine Block                   Sand                  5
10     Engine Block                Benzene                  6
11     Engine Block            Wheat Flour                  7
12     Packaged Kit           Coffee Beans                  2
13     Packaged Kit          Gypsum Boards                  9
14     Packaged Kit           Silicone Oil                  2

In [7]:
production_schedule_df

,prod_id,product_name,planned_start_date,planned_end_date,quantity,actual_end_date
0,1,Plastic Bottle,2025-09-01,2025-09-05,78,2025-09-05
1,2,Engine Block,2025-09-03,2025-09-07,95,2025-09-08
2,3,Packaged Kit,2025-09-05,2025-09-09,195,2025-09-09
3,4,Furniture Panel,2025-09-07,2025-09-11,160,2025-09-11
4,5,Plastic Bottle,2025-09-09,2025-09-13,102,2025-09-16
5,6,Engine Block,2025-09-11,2025-09-15,87,2025-09-16
6,7,Car Frame,2025-09-13,2025-09-17,193,2025-09-20
7,8,Engine Block,2025-09-15,2025-09-19,149,2025-09-22
8,9,Packaged Kit,2025-09-17,2025-09-21,143,2025-09-21
9,10,Plastic Bottle,2025-09-19,2025-09-23,171,2025-09-24

In [8]:
finished_goods_inventory_df

   fg_id     product_name  stock_level  reorder_point
0      1        Car Frame          170             75
1      2   Plastic Bottle          348             57
2      3  Furniture Panel          319             67
3      4     Engine Block          325             76
4      5     Packaged Kit          280            125

# Model

In [ ]:
embedding_model = HuggingFaceEmbeddings(model_name="thenlper/gte-large")